POST http://localhost:3001/api/persons
Content-Type: application/json

{
    "name": "Messi",
    "number": "040-1111111"
}

###

POST http://localhost:3001/api/persons
Content-Type: application/json

{
    "name": "Arto Hellas",
    "number": "040-1111111"
}

###

POST http://localhost:3001/api/persons
Content-Type: application/json

{
    "name": "messid10s",
    "number": "040-1111111"
}

###

POST http://localhost:3001/api/persons
Content-Type: application/json

{}