POST http://localhost:3003/api/blogs/6487a9c506891a06da011ae1/comments
Content-type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6ImZhdXN0byIsImlkIjoiNjQxNzVjNDU0NjRiODBkNjZlMmJiZTNiIiwiaWF0IjoxNjc5MjU2Nzc1fQ.0aS8pcYYaVwzaLf7ZZvNsK5Bpb_7Qw8yH0I-jVCgwZw 

{
    "comment": "soy un comentario"
}