POST http://localhost:3001/api/blogs
Content-type: application/json

{
    "title": "messi",
    "author": "messi",
    "url": "google.com",
    "likes": 2
}

###

POST http://localhost:3001/api/blogs
Content-type: application/json

{
    "title": "ronaldo",
    "author": "ronaldo",
    "url": "bing.com",
    "likes": 1
}

###

POST http://localhost:3001/api/blogs
Content-type: application/json

{
    "title": "riquelme",
    "author": "riquelme",
    "url": "bing.com"
}